theme: jekyll-theme-cayman
title: SpaceX

header_page_refs: ['Installation', 'Example', 'Hypothalamus']

# Build settings
markdown: kramdown
kramdown:
    math_engine:  katex

exclude:
  - LICENSE.md
  - README.md

