theme: jekyll-theme-cayman
title: SpaceX

header_page_refs: ['Installation', 'Example', 'Mouse_Hypothalamus_Data','Breast_Cancer_Data']

# Build settings
markdown: kramdown
kramdown:
    math_engine:  katex
exclude:
  - LICENSE.md
  - README.md

